# Generated by Django 4.2.4 on 2023-08-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_accessories_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessories',
            old_name='inventory',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='kidproducts',
            old_name='inventory',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='menproducts',
            old_name='inventory',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='womanproducts',
            old_name='inventory',
            new_name='stock',
        ),
    ]
