# Generated by Django 4.2.4 on 2023-08-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_accessory_name_accessories_model_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessories',
            old_name='discount',
            new_name='discount_Percentage',
        ),
        migrations.RenameField(
            model_name='kidproducts',
            old_name='discount',
            new_name='discount_Percentage',
        ),
        migrations.RenameField(
            model_name='menproducts',
            old_name='discount',
            new_name='discount_Percentage',
        ),
        migrations.RenameField(
            model_name='womanproducts',
            old_name='discount',
            new_name='discount_Percentage',
        ),
    ]
