# Generated by Django 4.2.4 on 2023-08-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_discount_accessories_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menproducts',
            name='approved',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=50, null=True),
        ),
    ]
