# Generated by Django 4.2.4 on 2023-08-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_accessories_approved_alter_comment_approved_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id'], name='products_co_content_4c675b_idx'),
        ),
    ]
